repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.5 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
     #- id: tflint # tflint always assumes latest, have to wait until all modules are 0.12.25 compatible
      - id: shellcheck
