AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketNameParameter:
    Type: String
    Description: Name of the S3 bucket to store backend state.
  TableNameParameter:
    Type: String
    Description: Name of the DynamoDB table to store state locks.
    
Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName:
        Ref: BucketNameParameter
      VersioningConfiguration:
        Status: Enabled

  TerraformLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
       Ref: TableNameParameter

Outputs:
  StackName:
    Value: !Ref AWS::StackName
  StateBucketName:
    Value: !Ref TerraformStateBucket
  LockTableName:
    Value: !Ref TerraformLockTable
